
--Levenshtein algorithm found in Python Jupyter


Select distinct Concat(First_name, ' ', Last_name) as Player
From Scratchdb_Research.[NM\NM287071].MLR2024Email me
order by 1
--"Adriaan Carelse","AJ Alatimu","Albert O'Shannessey","Alec McDonnell","Alessandro Heaney","Alex Glover","Alex Lopeti","Alexander Horan","Alexander Pohla-Murray","Aminae Amiatu-Tanoi","Andre Warner","Andrew Coe","Andrew Durutalo","Andrew Joseph Quattrin","Andrew Josh Henderson","Angus Hugh MacLellan","Anthem RC ","Anthem Rugby Carolina ","Asa Carter","Augusto Bohme","Austin White","Avery Oitomen","Axel Muller","Bailey Wilson","Bart Vermeulen","Ben LeSage","Ben Mitchell","Benjamin Bonasso","Benjamin Fry","Benjamin Landry","Benjamin Strang","Billy Meakes","Blair Cowan","Bradley Tucker","Brady Gilliland-Daniel","Braemar Murray","Brandon Harvey","Brian Flamenco","Brock Gallagher","Brooklyn Hardaker","Bruce Kauika-Petersen","Bruce Yun","Bryce Campbell","Cael Hodgson","Caleb Makene","Calixto Martinez","Callum Botchar","Cam Dolan","Cameron Davidowicz","Cameron Nelson","Cameron Nordli-Kelemeti","Cameron Orr","Caolan Dooley","Carlo de Nysschen","Cassh Maluia","Chance Wenglewski","Charles Abel","Charles Elton","Charles Hewitt","Charlie Overton","Chase Schor Haskin","Chase Suznevich","Chicago Hounds ","Christian Dyer","Christian Poidevin","Christopher Mattina","Christopher Mickelson","Christopher Quentin Newcomer","Christopher Turori","Cliven Loubser","Cole Keith","Collin Grosse","Conall Boomer","Conner Mooneyham","Connor Buckley","Connor Grindal","Connor Robinson","Connor Tupai","Connor Winchester","Conor Keys","Conor McManus","Conor Young","Cory Gilliland-Daniel","Cristian Rodriguez","Cullen Alex Maughan","Cyrille Cama","Dacoda Worth","Daemon Angel Torres","Dallas Jackals ","Damian Morley","Damian Stevens","Damien Hoyland","Dan Kriel","Dane Zander","Daniel Christensen","Daniel Hanson","Daniel Hollinshead","Daniel Pryor","Danny Tusitala","Danyon Morgan-Puterangi","DaQuan Perry","Darby Nelligan","Darcy Breen","David Beach","David Busby","David Coetzer","David Kearney","David Still","David Tameilau","Declan Moore","Derek Adams","Devereaux Ferris","Devin Short","Dewald Donald","Dewald Kotze","Diego Fortuny","Divan Rossouw","Djustice Sears-Duru","Dominic Akina","Dominick Iacovino","Dorian Jones","Douglas Fife","Drake Davis","Drew Wild","Duncan Matthews","Dylan Fawsitt","Dylan Fortune","Dylan Nel","Ed Fidow","Emerson Prior","Emmanuel Albert","Eric Naposki","Ethan Fryer","Ethan Grayson","Ethan McVeigh","Ezekiel Lindenmuth","Facundo Gattas","Fakaosifolau Pifeleti","Fatongia Paea","Felipe Etcheverry","Filimoni Waqainabete","Finn Kearns","Fintan Coleman","Foster Dewitt","Franco Palillo Neri","Franco van den Berg","Frank Lochore","Fred Apulu","Frederick De Beer","Gabe Casey","George Merrick","Gideon van Wyk","Gradyn Bowd","Graeme Pedegana","Gregory Peterson","Guillermo Leon Pujadas","Guiseppe du Toit","Harley Wheeler","Harris Rutherford","Henry Speight","Holden Yungert","Houston SaberCats ","Hugh Roach","Huw Taylor","Ignacio Dotti","Ignacio Peculo","Isaac Olson","Isaac Ross","Isaac Salmon","Isaia Kruse","Isaia Lotawa","Ishmail Shabazz","Ivan Pula","Jack Manzo","Jack Shaw","Jackson Thiebes","Jackson Zabierek","Jacobus Phillipus Snyman du Plessis","Jade Stighling","Jake Turnbull","Jamason Faanana-Schultz","James Irey","James Rivers","James Scott","James Stokes","James Vaifale","Janus Venter","Jarek Szopinski","Jarred Adams","Jason Damm","Jason Emery","Jason Higgins","Jason Robertson","Jason Tidwell","Javon Camp-Villalovos","Jay Renton","Jay Tuivaiti","Jayson Potroz","Jean Droste","Jed Melvin","Jerad Latu","Jeremiah Sio","Jeremy Misailegalu","Jeronimo Gomez Vara","Jesse Hamilton","Joaquin Horcada","Joe Basser","Joel Hodgson","Joeli Tikoisuva","Johan Momsen","John DuPree","John Jack Iscaro","John Jack Webster","John Poland","John Powers","John Rizzo","John-Roy Jenkinson","Jonah Auva'a","Jonah Dietenberger","Jonah Mauu","Jonas Petrakopoulos","Jordan Chait","Jordan Jackson-Hope","Joseph Mano","Joseph Taufete'e","Joseph Wrafter","Joshua Larsen","Joshua McAdam","Joshua Shetler","Juan Pablo Zeiss","Juan-Dee Oliver","Juan-Philip Smith","Julian Dominguez Widmer","Julian Roberts","Junior Gafa","Jurie van Vuuren","Justin Basson","Kaleb Geiger","Kalisi Moli","Kara Pryor","Kellen Gordon","Keni Nasoqeqe","Kian Matthew Meadon","Kieran Farmer","Kieran McClea","Killian Coghlan","Kirby Kenneth Perego Myhill","Koby Baker","Kullen Davis","Kyle Baillie","Kyle Breytenbach","Kyle Ciquera","Kyle Steeves","LaRome White","Lauina Futi","Lautaro Bavaro","Le Roux Malan","Liam Antrobus","Liam Murray","Lincoln Hook","Lincoln McClutchie","Lincoln Sii","Logan Weidner","Lolenisi Veimau","Lopeti Aisea","Los Angeles RFC ","Louis Conradie","Louis Kritzinger Van der Schyff","Lucas Bur","Lucas Gramlick","Lucas Rumball","Luke Campbell","Luke Carty","Luke Green","Luke White","Ma'a Nonu","Maciu Koroi","Mack Mason","Maclean Jones","Mahonri Ngakuru","Makeen Alikhan","Malakai Hala","Malcolm May","Manuel Ardao","Manuel Covella","Marcel Brache","Marcell Muller","Marcos Young","Mark O'Keeffe","Marno Redelinghuys","Marques Fualaau","Martin Elias","Martin Sigren Molina","Martin Vaca","Mason Flesch","Mason Koch","Mataiyasi Leuta","Mateo Gadsden","Matias Freyre","Matias Orlando","Matt Evans","Matt Giteau","Matthew Anticev","Matthew Harmon","Matthew Heaton","Matthew Jensen","Max Katjijeko","Max Schumacher","Miami Sharks ","Michael Baska","Michael Dabulas","Michael Etete","Michael Hand","Michael Manson","Michael Matarazzo","Michael Paseka Teo","Micheal Amiras","Mika Kruse","Mikaele Felix","Mitch Richardson","Mitchell Jacobson","Mitchell Wilson","Monate Akuei Gai","Nathan Den Hoedt","Nathaniel Augspurger","Nathaniel Sylvia","Nazareno Valentini","New England Free Jacks ","Niall Saunders","Nicholas Benn","Nicholas Feakes","Nicholas Grigg","Nicholas McCarthy","Nicklas Boyer","Nicolaas Maks van Dyk","Nicolas Elewaut","Nicolas Revol Pitt","Nicolas Souchon","Noah Bain","Noah Brown","NOLA Gold ","Olajuwon Noa","Old Glory DC ","Oliver Kane","Oliver Kilifi","Onehunga Havili Kaufusi","Osaiasi Tongaâ€™uiha","Oscar Koller","Oscar Lennon","Paddy Ryan","Pagopagohokma Haini","Palema Roberts","Patrick O'Toole","Patrick Ryan","Paul Lasike","Paul Mullen","Paula Balekana","Payton Telea Ilalio","Pedro Imhoff","Perry Humphreys","Peter Malcolm","Phillip Bradford","Piers Von Dadelszen","Pita Anae-Ah Sue","Ratu Veremalua Tuvere Vugakoto","Reagan Leslie","Reece Botha","Reece Macdonald","Reegan O'Gorman","Reid Davis","Reinaldo Piussi","RFC Los Angeles ","Rheno Taito'a","Rhyno Herbst","Rhys Jones","Richard Francis Rose","Riekert Hattingh","Rob Harley","Robert Cobb","Robert Povey","Rodney Esekia Iona","Roelof Andries Smit","Ronan Foley","Ronan Murphy","Ronnie McEligott","Rory Van Vugt","Ross Depperschmidt","Ryan James","Ryan Rees","Saia Uhila","Sam Matenga","Sam Reiner","Sam Walsh","Sam Windsor","Samuel Buckley","Samuel Golla","Samuel Hill","Samuel Israel Matenga","Samuel Klimkowski","Samuel Peri","Samuel Tuifua","San Diego Legion ","Santiago Videla","Sean McNulty","Sean Nolan","Sean Paranihi","Sean Ralph","Sean Yacoubian","Seattle Seawolves ","Sebastiano Villani","Sebastien Zaridze","Seimou Smith","Semi Kunabuli Kunatani","Semi Kunatani","Semise Tonga Kofe","Seth Purdey","Seth Smith","Setu A Vole","Shane Barry","Shane O'Leary","Shneil Singh","Siaosi Nai","Sidney Shoop","Sione Latu","Sione Mahe","Sitaleki Baker","Sosefo Joe Apikotoa","Spencer Jones","Stan van den Hoven","Steffan Crimp","Stephan Bernal-Wendt","Steven Longwell","Taniela Filimone","Tasman Smith","Taukiha'amea Koloamatangi","Tautalatasi Tasi","Tavite Lopeti","Taylor Krumrei","Te Rangatira Waitokia","Tesimoni Tongaâ€™uiha","Tevita Kuridrani","Tevita Naqali","Tevita Sole","Theo Vukasinovic","Thomas Tu'avao","Tiaan Erasmus","Tiaan Loots","Tinashe Muchena","Toby Fricker","Tom Florence","Tomalati Maafu","Tomas Aoake","Tomas Bekerman","Tomas Casares","Tomas Cubelli","Tomas Cubilla","Tomas Inciarte","Tomas Malanos","Tomasi Alosio","Tommaso Boni","Toni Pulu","Trenton Rogers","Tupou Afungia","Tyler Rowland","Tyler Wong","Tyren Malik Al-jiboori","Ulumu Niutupuivaha","Unaloto Tonga","Utah Warriors ","Valdermar Lee-Lo","Vaughen Isaacs","Viliami Helu","Wadood Agbongbon","Wayne van der Bank","Wian Conradie","William Leonard","William Talataina-Mu","William Waguespack","William Whiteside","Willis Goodwin","Wilton Rebolo","Zachary Bastres","Zion Going","Zurabi Zhvania"
Select distinct Player
From Scratchdb_Research.[NM\NM287071].MLR2024API
Order by 1
--"Adriaan Carelse","AJ Alatimu","Albert O'Shannessey","Ale Lopeti","Alec McDonnell","Alesana Pohla","Alex Glover","Alex Horan","Alex Maughan","Allesandro Heaney","Am'e Amiatu","Andre Warner","Andrew Coe","Andrew Durutalo","Andrew Quattrin","Angus MacLellan","Anthem Rugby Carolina","Asa Carter","Augusto Bohme","Austin White","Avery Oitomen","Axel Muller","Bailey Wilson","Bart Vermeulen","Ben Fry","Ben Landry","Ben LeSage","Ben Mitchell","Ben Strang","Benjamin Bonasso","Bill Whiteside","Billy Meakes","Blair Cowan","Brad Tucker","Brady Daniel","Braemar Murray","Brandon Harvey","Brian Flamenco","Brock Gallagher","Brooklyn Hardaker","Bruce Kuaika-Peterson","Bruce Yun","Bryce Campbell","Cael Hodgson","Caleb Makene","Cali Martinez","Callum Botchar","Cam Davidowicz","Cam Dolan","Cam Nelson","Cam Nordli-Kelemeti","Cameron Orr","Carlo de Nysschen","Cassh Maluia","Chance Wenglewski","Charles Elton","Charlie Abel","Charlie Hewitt","Chase Schor-Haskin","Chase Suznevich","Chicago Hounds","Chris Mattina","Chris Mickelson","Chris Turori","Christian Dyer","Christian Poidevin","Christian Rodriguez","Cliven Loubser","Coalan Dooley","Cole Keith","Collin Grosse","Conall Boomer","Conner Mooneyham","Connor Buckley","Connor Grindal","Connor Robinson","Connor Tupai","Connor Winchester","Conor Keys","Conor McManus","Conor Young","Cory Daniel","Cyrille Cama","Dacoda Worth","Daemon Torres","Dallas Jackals","Damian Morley","Damian Stevens","Damien Hoyland","Dan Hanson","Dan Hollinshead","Dan Kriel","Dan Pryor","Dane Zander","Danny Christensen","Danny Tusitala","Danyon Morgan-Puterangi","Daquan Perry","Darcy Breen","Dave Kearney","David Beach","David Busby","David Still","Davy Coetzer","Declan Moore","Derek Adams","Devereaux Ferris","Devin Short","Dewald Donald","Dewald Kotze","Diego Fortuny","Divan Rossouw","Djustice Sears-Duru","Dom Akina","Dominick Iaconvino","Dorian Jones","Dougie Fife","Drake Davis","Drew Wild","Duncan Matthews","Dylan Fawsitt","Dylan Fortune","Dylan Nel","Ed Fidow","Emerson Prior","Emmanuel Albert","Eric Naposki","Ethan Fryer","Ethan Grayson","Ethan McVeigh","Ezekiel Lindenmuth","Facundo Gattas","Faka'osi Pifeleti","Fatongia Paea","Felipe Etcheverry","Filimoni Waqainabete","Finn Kearns","Fintan Coleman","Foster Dewitt","Franco Palillo","Franco van den Berg","Frank Lochore","Fred Apulu","Frikkie de Beer","Gabriel Casey","George Merrick","Gideon van Wyk","Gradyn Bowd","Graeme Pedegana","Greg Peterson","Guillermo Pujadas","Guiseppe du Toit","Harley Wheeler","Harris Rutherford","Henry Speight","Holden Yungert","Houston SaberCats","Hugh Roach","Huw Taylor","Ignacio Dotti","Ignacio Peculo","Isaac Olson","Isaac Ross","Isaac Salmon","Isaia Kruse","Isaia Lotawa","Ishmail Shabazz","Ivan Pula","Jack Iscaro","Jack Manzo","Jack Shaw","Jack Webster","Jackson Thiebes","Jackson Zabierek","Jade Stighling","Jake Turnbull","Jamason Fa'anana-Schultz","James Irey","James Rivers","James Scott","James Stokes","James Vaifale","Janus Venter","Jarek Szopinski","Jarred Adams","Jason Damm","Jason Emery","Jason Higgins","Jason Robertson","Jason Tidwell","Javon Camp Villalovos","Jay Renton","Jay Tuivaiti","Jayson Potroz","Jean Droste","Jed Melvin","Jeremiah Sio","Jeremy Misailegalu","Jeronimo Gomez Vara","Jesse Hamilton","Joaquin Horcada","Joe Apikotoa","Joe Basser","Joe Mano","Joe Taufete'e","Joe Wrafter","Joel Hodgson","Joeli Tikoisuva","Johan Momsen","John Dupree","John Poland","John Powers","John Rizzo","John-Roy Jenkinson","Jonah Dietenberger","Jonah Mau'u","Jonas Petrakopoulos","Jordan Chait","Jordan Jackson-Hope","Josh Henderson","Josh Larsen","Josh McAdam","Josh Shetler","JP Du Plessis","JP Smith","Juan Dee Oliver","Juan Dee Olivier","Juan Pablo Zeiss","Julian Dominguez","Julian Roberts","Junior Gafa","Jurie van Vuuren","Justin Basson","Kaleb Geiger","Kalisi Moli","Kara Pryor","Kellen Gordon","Keni Nasoqeqe","Kian Meadon","Kieran Farmer","Kieran McClea","Killian Coghlan","Kirby Myhill","Koby Baker","KoiKoi Nelligan","Kyle Baillie","Kyle Breytenbach","Kyle Ciquera","Kyle Steeves","LaRome White","Lauina Futi","Lautaro Bavaro","Le Roux Malan","Liam Antrobus","Liam Murray","Lincoln McClutchie","Lincoln Si'i","Line Latu","Logan Weidner","Lolenisi Veimau","Lopeti Aisea","Louis Conradie","Louritz van der Schyff","Lucas Bur","Lucas Gramlick","Lucas Rumball","Luke Campbell","Luke Carty","Luke Green","Luke White","Ma'a Nonu","Maciu Koroi","Mack Mason","Maclean Jones","Mahonri Ngakuru","Makeen Alikham","Makeen Alikhan","Maks van Dyk","Malakai Hala-Ngatai","Malcolm May","Manuel Ardao","Manuel Covella","Marcel Brache","Marcell Muller","Marcos Young","Mark O'Keeffe","Marno Redelinghuys","Marques Fuala'au","Martin Elias","Martin Sigren","Martin Vaca","Mason Flesch","Mason Koch","Matai Leuta","Mateo Gadsden","Matias Freyre","Matias Orlando","Matt Anticev","Matt Giteau","Matt Harmon","Matt Heaton","Matt Jenson","Max Katjijeko","Max Schumacher","Miami Sharks","Michael Amiras","Michael Baska","Michael Etete","Michael Hand","Michael Maafu","Michael Manson","Mika Felix","Mika Kruse","Mike Dabulas","Mike Matarazzo","Mikey Te'o","Mitch Jacobson","Mitch Richardson","Mitch Wilson","Monatae Akuei Gai","Moni Tonga'uiha","Nate Augspurger","Nathan Den Hoedt","Nathan Sylvia","Nazareno Valentini","New England Free Jacks","Niall Saunders","Nic Benn","Nic Souchon","Nick Boyer","Nick Feakes","Nick Grigg","Nick McCarthy","Nicolas Elewaut","Nicolas Revol","Nicolas Revol Pitt","Noah Bain","Noah Brown","NOLA Gold","Olajuwon Noa","Old Glory DC","Olive Kilifi","Oliver Kane","Onehunga Havili","Osaiasi Tonga'uiha","Oscar Koller","Oscar Lennon","Paddy Ryan","Pago Haini","Palema Roberts","Pat O'Toole","Paul Lasike","Paul Mullen","Paula Balekana","Payton Telea-Ilalio","Pedro Imhoff","Perry Humphreys","Peter Malcolm","Phil Bradford","Piers von Dadelszen","Pita Ah Sue","Pono Davis","Quentin Newcomer","Reagan Leslie","Reece Botha","Reece Macdonald","Reegan O'Gorman","Reid Davis","Reinaldo Piussi","Rheno Teoni","Rhyno Herbst","Rhys Jones","Rick Rose","Riekert Hattingh","Rob Cobb","Rob Evans","Rob Harley","Robbie Povey","Rodney Iona","Roelof Smit","Ronan Foley","Ronan Murphy","Ronnie McElligot","Rory van Vugt","Ross Depperschmidt","Rugby FC Los Angeles","Ryan James","Ryan Rees","Saia Uhila","Sam Buckley","Sam Golla","Sam Hill","Sam Klimkowski","Sam Matenga","Sam Peri","Sam Reimer","Sam Tuifua","Sam Walsh","Sam Windsor","San Diego Legion","Santiago Videla","Sean McNulty","Sean Nolan","Sean Paranihi","Sean Ralph","Sean Yacoubian","Seattle Seawolves","Sebastiano Villani","Sebastien Zaridze","Seimou Smith","Semi Kunatani","Seta Baker","Seth Purdey","Seth Smith","Setu Vole","Shane Barry","Shane O'Leary","Shneil Singh","Siaosi Nai","Sidney Shoop","Sione Latu Jr","Sione Mahe","Spencer Jones","Stan van den Hoven","Stephan Bernal-Wendt","Stephan Crimp","Steven Longwell","Taniela Filimone","Tas Smith","Tau Koloamatangi","Tautalatasi Tasi","Tavite Lopeti","Taylor Krumrei","Te Rangatira Waitokia","Tevita Kuridrani","Tevita Naqali","Tevita Sole","Tevita Tameilau","Theo Vukasinovic","Thomas Tu'avao","Tiaan Erasmus","Tiaan Loots","Tinashe Muchena","Toby Fricker","Tom Florence","Tomas Aoake","Tomas Bekerman","Tomas Casares","Tomas Cubelli","Tomas Cubilla","Tomas Inciarte","Tomas Malanos","Tomasi Alosio","Tomasi Tonga","Tomiwa Agbongbon","Tommaso Boni","Tonga Kofe","Toni Pulu","Trent Rogers","Tupou Afungia","Tuvere Vugakoto","Ty Al-Jiboori","Tyler Rowland","Tyler Wong","Ulu Niuputuivaha","Utah Warriors","Valdemar Lee-Lo","Vaughan Isaacs","Vili Helu","Wayne van der Bank","Wian Conradie","Will Leonard","William Talataina","William Waguespack","Wilton Rebolo","Zach Bastres","Zion Going","Zura Zhivania"



Drop table if exists Scratchdb_Research.[NM\NM287071].LevenshteinDistanceStarter
Create table Scratchdb_Research.[NM\NM287071].LevenshteinDistanceStarter (
    full_name                   Varchar(50),
    Player                      Varchar(30),
    levDist                     Decimal(4,1)
);


INSERT INTO LevenshteinDistanceStarter (full_name, Player, levDist)
VALUES
('Adriaan Carelse', 'Adriaan Carelse', 0.0),
('AJ Alatimu', 'AJ Alatimu', 0.0),
('Albert O''Shannessey', 'Albert O''Shannessey', 0.0),
('Alec McDonnell', 'Alec McDonnell', 0.0),
('Alessandro Heaney', 'Allesandro Heaney', 2.0),
('Alex Glover', 'Alex Glover', 0.0),
('Alex Lopeti', 'Ale Lopeti', 1.0),
('Alexander Horan', 'Alex Horan', 5.0),
('Alexander Pohla-Murray', 'Alesana Pohla', 11.0),
('Aminae Amiatu-Tanoi', 'Am''e Amiatu', 9.0),
('Andre Warner', 'Andre Warner', 0.0),
('Andrew Coe', 'Andrew Coe', 0.0),
('Andrew Durutalo', 'Andrew Durutalo', 0.0),
('Andrew Joseph Quattrin', 'Andrew Quattrin', 7.0),
('Andrew Josh Henderson', 'Josh Henderson', 7.0),
('Angus Hugh MacLellan', 'Angus MacLellan', 5.0),
('Anthem RC ', 'Andrew Coe', 6.0),
('Anthem Rugby Carolina ', 'Anthem Rugby Carolina', 1.0),
('Asa Carter', 'Asa Carter', 0.0),
('Augusto Bohme', 'Augusto Bohme', 0.0),
('Austin White', 'Austin White', 0.0),
('Avery Oitomen', 'Avery Oitomen', 0.0),
('Axel Muller', 'Axel Muller', 0.0),
('Bailey Wilson', 'Bailey Wilson', 0.0),
('Bart Vermeulen', 'Bart Vermeulen', 0.0),
('Ben LeSage', 'Ben LeSage', 0.0),
('Ben Mitchell', 'Ben Mitchell', 0.0),
('Benjamin Bonasso', 'Benjamin Bonasso', 0.0),
('Benjamin Fry', 'Ben Fry', 5.0),
('Benjamin Landry', 'Ben Landry', 5.0),
('Benjamin Strang', 'Ben Strang', 5.0),
('Billy Meakes', 'Billy Meakes', 0.0),
('Blair Cowan', 'Blair Cowan', 0.0),
('Bradley Tucker', 'Brad Tucker', 3.0),
('Brady Gilliland-Daniel', 'Brady Daniel', 10.0),
('Braemar Murray', 'Braemar Murray', 0.0),
('Brandon Harvey', 'Brandon Harvey', 0.0),
('Brian Flamenco', 'Brian Flamenco', 0.0),
('Brock Gallagher', 'Brock Gallagher', 0.0),
('Brooklyn Hardaker', 'Brooklyn Hardaker', 0.0),
('Bruce Kauika-Petersen', 'Bruce Kuaika-Peterson', 3.0),
('Bruce Yun', 'Bruce Yun', 0.0),
('Bryce Campbell', 'Bryce Campbell', 0.0),
('Cael Hodgson', 'Cael Hodgson', 0.0),
('Caleb Makene', 'Caleb Makene', 0.0),
('Calixto Martinez', 'Cali Martinez', 3.0),
('Callum Botchar', 'Callum Botchar', 0.0),
('Cam Dolan', 'Cam Dolan', 0.0),
('Cameron Davidowicz', 'Cam Davidowicz', 4.0),
('Cameron Nelson', 'Cam Nelson', 4.0),
('Cameron Nordli-Kelemeti', 'Cam Nordli-Kelemeti', 4.0),
('Cameron Orr', 'Cameron Orr', 0.0),
('Caolan Dooley', 'Coalan Dooley', 2.0),
('Carlo de Nysschen', 'Carlo de Nysschen', 0.0),
('Cassh Maluia', 'Cassh Maluia', 0.0),
('Chance Wenglewski', 'Chance Wenglewski', 0.0),
('Charles Abel', 'Charlie Abel', 2.0),
('Charles Elton', 'Charles Elton', 0.0),
('Charles Hewitt', 'Charlie Hewitt', 2.0),
('Charlie Overton', 'Charlie Overton', 6.0),
('Chase Schor Haskin', 'Chase Schor-Haskin', 1.0),
('Chase Suznevich', 'Chase Suznevich', 0.0),
('Chicago Hounds ', 'Chicago Hounds', 1.0),
('Christian Dyer', 'Christian Dyer', 0.0),
('Christian Poidevin', 'Christian Poidevin', 0.0),
('Christopher Mattina', 'Chris Mattina', 6.0),
('Christopher Mickelson', 'Chris Mickelson', 6.0),
('Christopher Quentin Newcomer', 'Quentin Newcomer', 12.0),
('Christopher Turori', 'Chris Turori', 6.0),
('Cliven Loubser', 'Cliven Loubser', 0.0),
('Cole Keith', 'Cole Keith', 0.0),
('Collin Grosse', 'Collin Grosse', 0.0),
('Conall Boomer', 'Conall Boomer', 0.0),
('Conner Mooneyham', 'Conner Mooneyham', 0.0),
('Connor Buckley', 'Connor Buckley', 0.0),
('Connor Grindal', 'Connor Grindal', 0.0),
('Connor Robinson', 'Connor Robinson', 0.0),
('Connor Tupai', 'Connor Tupai', 0.0),
('Connor Winchester', 'Connor Winchester', 0.0),
('Conor Keys', 'Conor Keys', 0.0),
('Conor McManus', 'Conor McManus', 0.0),
('Conor Young', 'Conor Young', 0.0),
('Cory Gilliland-Daniel', 'Cory Daniel', 10.0),
('Cristian Rodriguez', 'Christian Rodriguez', 1.0),
('Cullen Alex Maughan', 'Alex Maughan', 7.0),
('Cyrille Cama', 'Cyrille Cama', 0.0),
('Dacoda Worth', 'Dacoda Worth', 0.0),
('Daemon Angel Torres', 'Daemon Torres', 6.0),
('Dallas Jackals ', 'Dallas Jackals', 1.0),
('Damian Morley', 'Damian Morley', 0.0),
('Damian Stevens', 'Damian Stevens', 0.0),
('Damien Hoyland', 'Damien Hoyland', 0.0),
('Dan Kriel', 'Dan Kriel', 0.0),
('Dane Zander', 'Dane Zander', 0.0),
('Daniel Christensen', 'Danny Christensen', 3.0),
('Daniel Hanson', 'Dan Hanson', 3.0),
('Daniel Hollinshead', 'Dan Hollinshead', 3.0),
('Daniel Pryor', 'Dan Pryor', 3.0),
('Danny Tusitala', 'Danny Tusitala', 0.0),
('Danyon Morgan-Puterangi', 'Danyon Morgan-Puterangi', 0.0),
('DaQuan Perry', 'Daquan Perry', 1.0),
('Darby Nelligan', 'KoiKoi Nelligan', 6.0),
('Darcy Breen', 'Darcy Breen', 0.0),
('David Beach', 'David Beach', 0.0),
('David Busby', 'David Busby', 0.0),
('David Coetzer', 'Davy Coetzer', 2.0),
('David Kearney', 'Dave Kearney', 2.0),
('David Still', 'David Still', 0.0),
('David Tameilau', 'Tevita Tameilau', 4.0),
('Declan Moore', 'Declan Moore', 0.0),
('Derek Adams', 'Derek Adams', 0.0),
('Devereaux Ferris', 'Devereaux Ferris', 0.0),
('Devin Short', 'Devin Short', 0.0),
('Dewald Donald', 'Dewald Donald', 0.0),
('Dewald Kotze', 'Dewald Kotze', 0.0),
('Diego Fortuny', 'Diego Fortuny', 0.0),
('Divan Rossouw', 'Divan Rossouw', 0.0),
('Djustice Sears-Duru', 'Djustice Sears-Duru', 0.0),
('Dominic Akina', 'Dom Akina', 4.0),
('Dominick Iacovino', 'Dominick Iaconvino', 1.0),
('Dorian Jones', 'Dorian Jones', 0.0),
('Douglas Fife', 'Dougie Fife', 3.0),
('Drake Davis', 'Drake Davis', 0.0),
('Drew Wild', 'Drew Wild', 0.0),
('Duncan Matthews', 'Duncan Matthews', 0.0),
('Dylan Fawsitt', 'Dylan Fawsitt', 0.0),
('Dylan Fortune', 'Dylan Fortune', 0.0),
('Dylan Nel', 'Dylan Nel', 0.0),
('Ed Fidow', 'Ed Fidow', 0.0),
('Emerson Prior', 'Emerson Prior', 0.0),
('Emmanuel Albert', 'Emmanuel Albert', 0.0),
('Eric Naposki', 'Eric Naposki', 0.0),
('Ethan Fryer', 'Ethan Fryer', 0.0),
('Ethan Grayson', 'Ethan Grayson', 0.0),
('Ethan McVeigh', 'Ethan McVeigh', 0.0),
('Ezekiel Lindenmuth', 'Ezekiel Lindenmuth', 0.0),
('Facundo Gattas', 'Facundo Gattas', 0.0),
('Fakaosifolau Pifeleti', 'Faka''osi Pifeleti', 6.0),
('Fatongia Paea', 'Fatongia Paea', 0.0),
('Felipe Etcheverry', 'Felipe Etcheverry', 0.0),
('Filimoni Waqainabete', 'Filimoni Waqainabete', 0.0),
('Finn Kearns', 'Finn Kearns', 0.0),
('Fintan Coleman', 'Fintan Coleman', 0.0),
('Foster Dewitt', 'Foster Dewitt', 0.0),
('Franco Palillo Neri', 'Franco Palillo', 5.0),
('Franco van den Berg', 'Franco van den Berg', 0.0),
('Frank Lochore', 'Frank Lochore', 0.0),
('Fred Apulu', 'Fred Apulu', 0.0),
('Frederick De Beer', 'Frikkie de Beer', 7.0),
('Gabe Casey', 'Gabriel Casey', 3.0),
('George Merrick', 'George Merrick', 0.0),
('Gideon van Wyk', 'Gideon van Wyk', 0.0),
('Gradyn Bowd', 'Gradyn Bowd', 0.0),
('Graeme Pedegana', 'Graeme Pedegana', 0.0),
('Gregory Peterson', 'Greg Peterson', 3.0),
('Guillermo Leon Pujadas', 'Guillermo Pujadas', 5.0),
('Guiseppe du Toit', 'Guiseppe du Toit', 0.0),
('Harley Wheeler', 'Harley Wheeler', 0.0),
('Harris Rutherford', 'Harris Rutherford', 0.0),
('Henry Speight', 'Henry Speight', 0.0),
('Holden Yungert', 'Holden Yungert', 0.0),
('Houston SaberCats ', 'Houston SaberCats', 1.0),
('Hugh Roach', 'Hugh Roach', 0.0),
('Huw Taylor', 'Huw Taylor', 0.0),
('Ignacio Dotti', 'Ignacio Dotti', 0.0),
('Ignacio Peculo', 'Ignacio Peculo', 0.0),
('Isaac Olson', 'Isaac Olson', 0.0),
('Isaac Ross', 'Isaac Ross', 0.0),
('Isaac Salmon', 'Isaac Salmon', 0.0),
('Isaia Kruse', 'Isaia Kruse', 0.0),
('Isaia Lotawa', 'Isaia Lotawa', 0.0),
('Ishmail Shabazz', 'Ishmail Shabazz', 0.0),
('Ivan Pula', 'Ivan Pula', 0.0),
('Jack Manzo', 'Jack Manzo', 0.0),
('Jack Shaw', 'Jack Shaw', 0.0),
('Jackson Thiebes', 'Jackson Thiebes', 0.0),
('Jackson Zabierek', 'Jackson Zabierek', 0.0),
('Jacobus Phillipus Snyman du Plessis', 'JP Du Plessis', 23.0),
('Jade Stighling', 'Jade Stighling', 0.0),
('Jake Turnbull', 'Jake Turnbull', 0.0),
('Jamason Faanana-Schultz', 'Jamason Fa''anana-Schultz', 1.0),
('James Irey', 'James Irey', 0.0),
('James Rivers', 'James Rivers', 0.0),
('James Scott', 'James Scott', 0.0),
('James Stokes', 'James Stokes', 0.0),
('James Vaifale', 'James Vaifale', 0.0),
('Janus Venter', 'Janus Venter', 0.0),
('Jarek Szopinski', 'Jarek Szopinski', 0.0),
('Jarred Adams', 'Jarred Adams', 0.0),
('Jason Damm', 'Jason Damm', 0.0),
('Jason Emery', 'Jason Emery', 0.0),
('Jason Higgins', 'Jason Higgins', 0.0),
('Jason Robertson', 'Jason Robertson', 0.0),
('Jason Tidwell', 'Jason Tidwell', 0.0),
('Javon Camp-Villalovos', 'Javon Camp Villalovos', 1.0),
('Jay Renton', 'Jay Renton', 0.0),
('Jay Tuivaiti', 'Jay Tuivaiti', 0.0),
('Jayson Potroz', 'Jayson Potroz', 0.0),
('Jean Droste', 'Jean Droste', 0.0),
('Jed Melvin', 'Jed Melvin', 0.0),
('Jerad Latu', 'Line Latu', 5.0),
('Jeremiah Sio', 'Jeremiah Sio', 0.0),
('Jeremy Misailegalu', 'Jeremy Misailegalu', 0.0),
('Jeronimo Gomez Vara', 'Jeronimo Gomez Vara', 0.0),
('Jesse Hamilton', 'Jesse Hamilton', 0.0),
('Joaquin Horcada', 'Joaquin Horcada', 0.0),
('Joe Basser', 'Joe Basser', 0.0),
('Joel Hodgson', 'Joel Hodgson', 0.0),
('Joeli Tikoisuva', 'Joeli Tikoisuva', 0.0),
('Johan Momsen', 'Johan Momsen', 0.0),
('John DuPree', 'John Dupree', 1.0),
('John Jack Iscaro', 'Jack Iscaro', 5.0),
('John Jack Webster', 'Jack Webster', 5.0),
('John Poland', 'John Poland', 0.0),
('John Powers', 'John Powers', 0.0),
('John Rizzo', 'John Rizzo', 0.0),
('John-Roy Jenkinson', 'John-Roy Jenkinson', 0.0),
('Jonah Auva''a', 'Jonah Auva''a', 0.0),
('Jonah Dietenberger', 'Jonah Dietenberger', 0.0),
('Jonah Mauu', 'Jonah Mau''u', 1.0),
('Jonas Petrakopoulos', 'Jonas Petrakopoulos', 0.0),
('Jordan Chait', 'Jordan Chait', 0.0),
('Jordan Jackson-Hope', 'Jordan Jackson-Hope', 0.0),
('Joseph Mano', 'Joe Mano', 3.0),
('Joseph Taufete''e', 'Joe Taufete''e', 3.0),
('Joseph Wrafter', 'Joe Wrafter', 3.0),
('Joshua Larsen', 'Josh Larsen', 2.0),
('Joshua McAdam', 'Josh McAdam', 2.0),
('Joshua Shetler', 'Josh Shetler', 2.0),
('Juan Pablo Zeiss', 'Juan Pablo Zeiss', 0.0),
('Juan-Dee Oliver', 'Juan Dee Oliver', 1.0),
('Juan-Philip Smith', 'JP Smith', 9.0),
('Julian Dominguez Widmer', 'Julian Dominguez', 7.0),
('Julian Roberts', 'Julian Roberts', 0.0),
('Junior Gafa', 'Junior Gafa', 0.0),
('Jurie van Vuuren', 'Jurie van Vuuren', 0.0),
('Justin Basson', 'Justin Basson', 0.0),
('Kaleb Geiger', 'Kaleb Geiger', 0.0),
('Kalisi Moli', 'Kalisi Moli', 0.0),
('Kara Pryor', 'Kara Pryor', 0.0),
('Kellen Gordon', 'Kellen Gordon', 0.0),
('Keni Nasoqeqe', 'Keni Nasoqeqe', 0.0),
('Kian Matthew Meadon', 'Kian Meadon', 8.0),
('Kieran Farmer', 'Kieran Farmer', 0.0),
('Kieran McClea', 'Kieran McClea', 0.0),
('Killian Coghlan', 'Killian Coghlan', 0.0),
('Kirby Kenneth Perego Myhill', 'Kirby Myhill', 15.0),
('Koby Baker', 'Koby Baker', 0.0),
('Kullen Davis', 'Pono Davis', 5.0),
('Kyle Baillie', 'Kyle Baillie', 0.0),
('Kyle Breytenbach', 'Kyle Breytenbach', 0.0),
('Kyle Ciquera', 'Kyle Ciquera', 0.0),
('Kyle Steeves', 'Kyle Steeves', 0.0),
('LaRome White', 'LaRome White', 0.0),
('Lauina Futi', 'Lauina Futi', 0.0),
('Lautaro Bavaro', 'Lautaro Bavaro', 0.0),
('Le Roux Malan', 'Le Roux Malan', 0.0),
('Liam Antrobus', 'Liam Antrobus', 0.0),
('Liam Murray', 'Liam Murray', 0.0),
('Lincoln Hook', 'Lincoln McClutchie', 4.0), --fixed from Si'i
('Lincoln McClutchie', 'Lincoln McClutchie', 0.0),
('Lincoln Sii', 'Lincoln Si''i', 1.0),
('Logan Weidner', 'Logan Weidner', 0.0),
('Lolenisi Veimau', 'Lolenisi Veimau', 0.0),
('Lopeti Aisea', 'Lopeti Aisea', 0.0),
('Los Angeles RFC ', 'Rugby FC Los Angeles', 11.0),
('Louis Conradie', 'Louis Conradie', 0.0),
('Louis Kritzinger Van der Schyff', 'Louritz van der Schyff', 10.0),
('Lucas Bur', 'Lucas Bur', 0.0),
('Lucas Gramlick', 'Lucas Gramlick', 0.0),
('Lucas Rumball', 'Lucas Rumball', 0.0),
('Luke Campbell', 'Luke Campbell', 0.0),
('Luke Carty', 'Luke Carty', 0.0),
('Luke Green', 'Luke Green', 0.0),
('Luke White', 'Luke White', 0.0),
('Ma''a Nonu', 'Ma''a Nonu', 0.0),
('Maciu Koroi', 'Maciu Koroi', 0.0),
('Mack Mason', 'Mack Mason', 0.0),
('Maclean Jones', 'Maclean Jones', 0.0),
('Mahonri Ngakuru', 'Mahonri Ngakuru', 0.0),
('Makeen Alikhan', 'Makeen Alikhan', 0.0),
('Malakai Hala', 'Malakai Hala-Ngatai', 7.0),
('Malcolm May', 'Malcolm May', 0.0),
('Manuel Ardao', 'Manuel Ardao', 0.0),
('Manuel Covella', 'Manuel Covella', 0.0),
('Marcel Brache', 'Marcel Brache', 0.0),
('Marcell Muller', 'Marcell Muller', 0.0),
('Marcos Young', 'Marcos Young', 0.0),
('Mark O''Keeffe', 'Mark O''Keeffe', 0.0),
('Marno Redelinghuys', 'Marno Redelinghuys', 0.0),
('Marques Fualaau', 'Marques Fuala''au', 1.0),
('Martin Elias', 'Martin Elias', 0.0),
('Martin Sigren Molina', 'Martin Sigren', 7.0),
('Martin Vaca', 'Martin Vaca', 0.0),
('Mason Flesch', 'Mason Flesch', 0.0),
('Mason Koch', 'Mason Koch', 0.0),
('Mataiyasi Leuta', 'Matai Leuta', 4.0),
('Mateo Gadsden', 'Mateo Gadsden', 0.0),
('Matias Freyre', 'Matias Freyre', 0.0),
('Matias Orlando', 'Matias Orlando', 0.0),
('Matt Evans', 'Rob Evans', 4.0),
('Matt Giteau', 'Matt Giteau', 0.0),
('Matthew Anticev', 'Matt Anticev', 3.0),
('Matthew Harmon', 'Matt Harmon', 3.0),
('Matthew Heaton', 'Matt Heaton', 3.0),
('Matthew Jensen', 'Matt Jenson', 4.0),
('Max Katjijeko', 'Max Katjijeko', 0.0),
('Max Schumacher', 'Max Schumacher', 0.0),
('Miami Sharks ', 'Miami Sharks', 1.0),
('Michael Baska', 'Michael Baska', 0.0),
('Michael Dabulas', 'Mike Dabulas', 4.0),
('Michael Etete', 'Michael Etete', 0.0),
('Michael Hand', 'Michael Hand', 0.0),
('Michael Manson', 'Michael Manson', 0.0),
('Michael Matarazzo', 'Mike Matarazzo', 4.0),
('Michael Paseka Teo', 'Mikey Te''o', 6.0),
('Micheal Amiras', 'Michael Amiras', 2.0),
('Mika Kruse', 'Mika Kruse', 0.0),
('Mikaele Felix', 'Mika Felix', 3.0),
('Mitch Richardson', 'Mitch Richardson', 0.0),
('Mitchell Jacobson', 'Mitch Jacobson', 3.0),
('Mitchell Wilson', 'Mitch Wilson', 3.0),
('Monate Akuei Gai', 'Monatae Akuei Gai', 1.0),
('Nathan Den Hoedt', 'Nathan Den Hoedt', 0.0),
('Nathaniel Augspurger', 'Nate Augspurger', 5.0),
('Nathaniel Sylvia', 'Nathan Sylvia', 3.0),
('Nazareno Valentini', 'Nazareno Valentini', 0.0),
('New England Free Jacks ', 'New England Free Jacks', 1.0),
('Niall Saunders', 'Niall Saunders', 0.0),
('Nicholas Benn', 'Nic Benn', 5.0),
('Nicholas Feakes', 'Nick Feakes', 5.0),
('Nicholas Grigg', 'Nick Grigg', 5.0),
('Nicholas McCarthy', 'Nick McCarthy', 5.0),
('Nicklas Boyer', 'Nick Boyer', 3.0),
('Nicolaas Maks van Dyk', 'Maks van Dyk', 9.0),
('Nicolas Elewaut', 'Nicolas Elewaut', 0.0),
('Nicolas Revol Pitt', 'Nicolas Revol Pitt', 0.0),
('Nicolas Souchon', 'Nic Souchon', 4.0),
('Noah Bain', 'Noah Bain', 0.0),
('Noah Brown', 'Noah Brown', 0.0),
('NOLA Gold ', 'NOLA Gold', 1.0),
('Olajuwon Noa', 'Olajuwon Noa', 0.0),
('Old Glory DC ', 'Old Glory DC', 1.0),
('Oliver Kane', 'Oliver Kane', 0.0),
('Oliver Kilifi', 'Olive Kilifi', 1.0),
('Onehunga Havili Kaufusi', 'Onehunga Havili', 8.0),
('Osaiasi Tongaâ€™uiha', 'Osaiasi Tonga''uiha', 3.0),
('Oscar Koller', 'Oscar Koller', 0.0),
('Oscar Lennon', 'Oscar Lennon', 0.0),
('Paddy Ryan', 'Paddy Ryan', 0.0),
('Paddy Ryan_SDL', 'Paddy Ryan_CHI', 0.0),
('Paddy Ryan_CHI', 'Paddy Ryan_SDL', 0.0),
('Pagopagohokma Haini', 'Pago Haini', 9.0),
('Palema Roberts', 'Palema Roberts', 0.0),
('Patrick O''Toole', 'Pat O''Toole', 4.0),
('Patrick Ryan', 'Paddy Ryan', 5.0),
('Paul Lasike', 'Paul Lasike', 0.0),
('Paul Mullen', 'Paul Mullen', 0.0),
('Paula Balekana', 'Paula Balekana', 0.0),
('Payton Telea Ilalio', 'Payton Telea-Ilalio', 1.0),
('Pedro Imhoff', 'Pedro Imhoff', 0.0),
('Perry Humphreys', 'Perry Humphreys', 0.0),
('Peter Malcolm', 'Peter Malcolm', 0.0),
('Phillip Bradford', 'Phil Bradford', 3.0),
('Piers Von Dadelszen', 'Piers von Dadelszen', 1.0),
('Pita Anae-Ah Sue', 'Pita Ah Sue', 5.0),
('Ratu Veremalua Tuvere Vugakoto', 'Tuvere Vugakoto', 15.0),
('Reagan Leslie', 'Reagan Leslie', 0.0),
('Reece Botha', 'Reece Botha', 0.0),
('Reece Macdonald', 'Reece Macdonald', 0.0),
('Reegan O''Gorman', 'Reegan O''Gorman', 0.0),
('Reid Davis', 'Reid Davis', 0.0),
('Reinaldo Piussi', 'Reinaldo Piussi', 0.0),
('RFC Los Angeles ', 'Rugby FC Los Angeles', 6.0),
('Rheno Taito''a', 'Rheno Teoni', 5.0),
('Rhyno Herbst', 'Rhyno Herbst', 0.0),
('Rhys Jones', 'Rhys Jones', 0.0),
('Richard Francis Rose', 'Rick Rose', 11.0), --fixed from Michael Manson
('Riekert Hattingh', 'Riekert Hattingh', 0.0),
('Rob Harley', 'Rob Harley', 0.0),
('Robert Cobb', 'Rob Cobb', 3.0),
('Robert Povey', 'Robbie Povey', 3.0),
('Rodney Esekia Iona', 'Rodney Iona', 7.0),
('Roelof Andries Smit', 'Roelof Smit', 8.0),
('Ronan Foley', 'Ronan Foley', 0.0),
('Ronan Murphy', 'Ronan Murphy', 0.0),
('Ronnie McEligott', 'Ronnie McElligot', 2.0),
('Rory Van Vugt', 'Rory van Vugt', 1.0),
('Ross Depperschmidt', 'Ross Depperschmidt', 0.0),
('Ryan James', 'Ryan James', 0.0),
('Ryan Rees', 'Ryan Rees', 0.0),
('Saia Uhila', 'Saia Uhila', 0.0),
('Sam Matenga', 'Sam Matenga', 0.0),
('Sam Reiner', 'Sam Reimer', 1.0),
('Sam Walsh', 'Sam Walsh', 0.0),
('Sam Windsor', 'Sam Windsor', 0.0),
('Samuel Buckley', 'Sam Buckley', 3.0),
('Samuel Golla', 'Sam Golla', 3.0),
('Samuel Hill', 'Sam Hill', 3.0),
('Samuel Israel Matenga', 'Sam Matenga', 10.0),
('Samuel Klimkowski', 'Sam Klimkowski', 3.0),
('Samuel Peri', 'Sam Peri', 3.0),
('Samuel Tuifua', 'Sam Tuifua', 3.0),
('San Diego Legion ', 'San Diego Legion', 1.0),
('Santiago Videla', 'Santiago Videla', 0.0),
('Sean McNulty', 'Sean McNulty', 0.0),
('Sean Nolan', 'Sean Nolan', 0.0),
('Sean Paranihi', 'Sean Paranihi', 0.0),
('Sean Ralph', 'Sean Ralph', 0.0),
('Sean Yacoubian', 'Sean Yacoubian', 0.0),
('Seattle Seawolves ', 'Seattle Seawolves', 1.0),
('Sebastiano Villani', 'Sebastiano Villani', 0.0),
('Sebastien Zaridze', 'Sebastien Zaridze', 0.0),
('Seimou Smith', 'Seimou Smith', 0.0),
('Semi Kunabuli Kunatani', 'Semi Kunatani', 9.0),
('Semi Kunatani', 'Semi Kunatani', 0.0),
('Semise Tonga Kofe', 'Tonga Kofe', 7.0),
('Seth Purdey', 'Seth Purdey', 0.0),
('Seth Smith', 'Seth Smith', 0.0),
('Setu A Vole', 'Setu Vole', 2.0),
('Shane Barry', 'Shane Barry', 0.0),
('Shane O''Leary', 'Shane O''Leary', 0.0),
('Shneil Singh', 'Shneil Singh', 0.0),
('Siaosi Nai', 'Siaosi Nai', 0.0),
('Sidney Shoop', 'Sidney Shoop', 0.0),
('Sione Latu', 'Sione Latu Jr', 2.0),
('Sione Mahe', 'Sione Mahe', 0.0),
('Sitaleki Baker', 'Seta Baker', 5.0),
('Sosefo Joe Apikotoa', 'Joe Apikotoa', 7.0),
('Spencer Jones', 'Spencer Jones', 0.0),
('Stan van den Hoven', 'Stan van den Hoven', 0.0),
('Steffan Crimp', 'Stephan Crimp', 2.0),
('Stephan Bernal-Wendt', 'Stephan Bernal-Wendt', 0.0),
('Steven Longwell', 'Steven Longwell', 0.0),
('Taniela Filimone', 'Taniela Filimone', 0.0),
('Tasman Smith', 'Tas Smith', 3.0),
('Taukiha''amea Koloamatangi', 'Tau Koloamatangi', 9.0),
('Tautalatasi Tasi', 'Tautalatasi Tasi', 0.0),
('Tavite Lopeti', 'Tavite Lopeti', 0.0),
('Taylor Krumrei', 'Taylor Krumrei', 0.0),
('Te Rangatira Waitokia', 'Te Rangatira Waitokia', 0.0),
('Tesimoni Tongaâ€™uiha', 'Moni Tonga''uiha', 8.0),
('Tevita Kuridrani', 'Tevita Kuridrani', 0.0),
('Tevita Naqali', 'Tevita Naqali', 0.0),
('Tevita Sole', 'Tevita Sole', 0.0),
('Theo Vukasinovic', 'Theo Vukasinovic', 0.0),
('Thomas Tu''avao', 'Thomas Tu''avao', 0.0),
('Tiaan Erasmus', 'Tiaan Erasmus', 0.0),
('Tiaan Loots', 'Tiaan Loots', 0.0),
('Tinashe Muchena', 'Tinashe Muchena', 0.0),
('Toby Fricker', 'Toby Fricker', 0.0),
('Tom Florence', 'Tom Florence', 0.0),
('Tomalati Maafu', 'Michael Maafu', 7.0),
('Tomas Aoake', 'Tomas Aoake', 0.0),
('Tomas Bekerman', 'Tomas Bekerman', 0.0),
('Tomas Casares', 'Tomas Casares', 0.0),
('Tomas Cubelli', 'Tomas Cubelli', 0.0),
('Tomas Cubilla', 'Tomas Cubilla', 0.0),
('Tomas Inciarte', 'Tomas Inciarte', 0.0),
('Tomas Malanos', 'Tomas Malanos', 0.0),
('Tomasi Alosio', 'Tomasi Alosio', 0.0),
('Tommaso Boni', 'Tommaso Boni', 0.0),
('Toni Pulu', 'Toni Pulu', 0.0),
('Trenton Rogers', 'Trent Rogers', 2.0),
('Tupou Afungia', 'Tupou Afungia', 0.0),
('Tyler Rowland', 'Tyler Rowland', 0.0),
('Tyler Wong', 'Tyler Wong', 0.0),
('Tyren Malik Al-jiboori', 'Ty Al-Jiboori', 10.0),
('Ulumu Niutupuivaha', 'Ulu Niuputuivaha', 4.0),
('Unaloto Tonga', 'Tomasi Tonga', 7.0),
('Utah Warriors ', 'Utah Warriors', 1.0),
('Valdermar Lee-Lo', 'Valdemar Lee-Lo', 1.0),
('Vaughen Isaacs', 'Vaughan Isaacs', 1.0),
('Viliami Helu', 'Vili Helu', 3.0),
('Wadood Agbongbon', 'Tomiwa Agbongbon', 6.0),
('Wayne van der Bank', 'Wayne van der Bank', 0.0),
('Wian Conradie', 'Wian Conradie', 0.0),
('William Leonard', 'Will Leonard', 3.0),
('William Talataina-Mu', 'William Talataina', 3.0),
('William Waguespack', 'William Waguespack', 0.0),
('William Whiteside', 'Bill Whiteside', 4.0),
('Willis Goodwin', 'Willis Goodwin', 7.0),
('Wilton Rebolo', 'Wilton Rebolo', 0.0),
('Zachary Bastres', 'Zach Bastres', 3.0),
('Zion Going', 'Zion Going', 0.0),
('Zurabi Zhvania', 'Zura Zhivania', 3.0)


Select *
From Scratchdb_Research.[NM\NM287071].LevenshteinDistanceStarter lvs
